Upgrade dependencies
The most critical upgrade is that of jide-oss as it resolves a
NoClassDefFoundError for WindowsLookAndFeel when switching to a theme
other than Metal on a Linux machine.